title: Muldoon
description: A package for sifting meteorological data to look for and analyze vortex encounters
show_downloads: true
google_analytics:
google_analytics_anonymize: false
darkmode: false
remote_theme: tuur29/pages-themes-cayman
#theme: jekyll-theme-cayman
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

# hide_first_title: false # Useful if README.md is used on both github and pages
# logo_url: ./logo.png # Either absolute or relative url
# syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet

colors:
    gradient_left: "#873e23"    # default: #155799
    gradient_right: "#e28743"   # default: #159957
    header: "#fff"              # default: #fff 
    android_theme: "#000"       # default: #000
    link: "#1e6bb8"             # default: #136bb8
    section_title: "#155799"    # default: #155799
buttons:
      github_hide: false        # hides "View on Github"
      zip_url:
      zip_title:                # default "Download .zip"
      zip_hide: false           # hides "Download .zip
      tar_url:
      tar_title:                # default "Download .tar.gz"
      tar_hide: false           # hides "Download .tar.gz"
