title: Muldoon
description: A package for sifting meteorological data to look for and analyze vortex encounters
show_downloads: true
google_analytics:
google_analytics_anonymize: false
darkmode: false
theme: jekyll-theme-cayman
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false


# hide_first_title: false # Useful if README.md is used on both github and pages
# logo_url: ./logo.png # Either absolute or relative url
# syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet

colors:
    gradient_left: "#155799"    # this defaults to #155799
    gradient_right: "#159957"   # this defaults to #159957
    header: "#fff"              # this defaults to 
    android_theme: "#000"       # this defaults to gradient_color
    link: "#1e6bb8"             # this defaults to gradient_color
    section_title: "#155799"    # this defaults to gradient_color
buttons:
      github_title: Documention             # default "View on Github"
      github_hide: false        # hides "View on Github"
      zip_url:
      zip_title:                # default "Download .zip"
      zip_hide: false           # hides "Download .zip
      tar_url:
      tar_title:                # default "Download .tar.gz"
      tar_hide: false           # hides "Download .tar.gz"
